/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "aerietajekoijceknbbk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlcmlldGFqZWtvaWpjZWtuYmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMjk4MTcsImV4cCI6MjA4NjkwNTgxN30.jKu4nVwdijEwd_OlcJL-gpy6VDM3nxQT-s0ne73QACs"